{
 "title": "StecaGrid Inverter",
 "description": "StecaGrid Inverter metrics",
 "time": { "from": "2022-10-11T19:21:47.505Z", "to": "2022-10-11T20:21:47.506Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Direct Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "DC Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "stecagrid_dc_current", "legendFormat": "dc_current" }
   ]
  },
  {
   "title": "DC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "stecagrid_dc_voltage", "legendFormat": "dc_voltage" }
   ]
  },
  { "title": "Alternating Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AC Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "stecagrid_ac_frequency", "legendFormat": "ac_frequency" }
   ]
  },
  {
   "title": "AC Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "stecagrid_ac_current", "legendFormat": "ac_current" }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "timeseries",
   "description": "Volt",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "stecagrid_ac_voltage", "legendFormat": "ac_voltage" }
   ]
  },
  {
   "title": "AC Power",
   "type": "timeseries",
   "description": "AC Power in Watt",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "stecagrid_ac_power", "legendFormat": "ac_power" }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stecagrid_temp", "legendFormat": "dc_voltage" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Internal inverter temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "stecagrid_temp", "legendFormat": "temperature" }
   ]
  }
 ]
}